package jp.alticeworks.townymarket.service;

import jp.alticeworks.townymarket.storage.Database;
import org.bukkit.entity.Player;
import java.nio.charset.StandardCharsets;
import java.security.*;
import java.sql.*;
import java.util.*;

public final class CorporateOperations {
    private static final Set<String> RELATIONS=Set.of("良","普","嫌","同","提","子","親");
    private final Database db;
    public CorporateOperations(Database db){this.db=db;}
    public boolean canManage(Player p,String company){try{String uuid=p.getUniqueId().toString();try(PreparedStatement q=db.connection().prepareStatement("SELECT owner FROM companies WHERE id=? OR name=?")){q.setString(1,company);q.setString(2,company);try(ResultSet r=q.executeQuery()){if(!r.next())return false;if(uuid.equals(r.getString(1)))return true;}}try(PreparedStatement q=db.connection().prepareStatement("SELECT role,permissions FROM company_roles cr JOIN companies c ON c.id=cr.company_id WHERE (c.id=? OR c.name=?) AND cr.player=?")){q.setString(1,company);q.setString(2,company);q.setString(3,uuid);try(ResultSet r=q.executeQuery()){if(!r.next())return false;String role=r.getString(1).toUpperCase();String perms=r.getString(2);return Set.of("PRESIDENT","CHAIRMAN","CEO","DIRECTOR").contains(role)||perms.contains("company.manage")||perms.contains("*");}}}catch(SQLException e){return false;}}
    public String setPasscode(Player p,String code){if(code==null||!code.matches("\\d{6,12}"))return "取引パスコードは6〜12桁の数字です。";try{byte[] salt=new byte[16];new SecureRandom().nextBytes(salt);byte[] hash=hash(code,salt);try(PreparedStatement s=db.connection().prepareStatement("INSERT INTO transaction_passcodes(player,pass_hash,updated_at) VALUES(?,?,?) ON CONFLICT(player) DO UPDATE SET pass_hash=excluded.pass_hash,updated_at=excluded.updated_at")){s.setString(1,p.getUniqueId().toString());s.setString(2,Base64.getEncoder().encodeToString(salt)+":"+Base64.getEncoder().encodeToString(hash));s.setLong(3,System.currentTimeMillis());s.executeUpdate();}return "取引パスコードを設定しました。";}catch(Exception e){return "パスコード設定に失敗しました。";}}
    public boolean verifyPasscode(Player p,String code){try(PreparedStatement q=db.connection().prepareStatement("SELECT pass_hash FROM transaction_passcodes WHERE player=?")){q.setString(1,p.getUniqueId().toString());try(ResultSet r=q.executeQuery()){if(!r.next())return false;String[] v=r.getString(1).split(":");return MessageDigest.isEqual(hash(code,Base64.getDecoder().decode(v[0])),Base64.getDecoder().decode(v[1]));}}catch(Exception e){return false;}}
    private byte[] hash(String code,byte[] salt)throws GeneralSecurityException{javax.crypto.SecretKeyFactory f=javax.crypto.SecretKeyFactory.getInstance("PBKDF2WithHmacSHA256");return f.generateSecret(new javax.crypto.spec.PBEKeySpec(code.toCharArray(),salt,120000,256)).getEncoded();}
    public String requestApproval(Player p,String ref){if(!p.isOp())return "管理者権限が必要です。";try(PreparedStatement i=db.connection().prepareStatement("INSERT INTO transaction_approvals(id,transaction_ref,requester,status,created_at) VALUES(?,?,?,?,?)")){i.setString(1,UUID.randomUUID().toString());i.setString(2,ref);i.setString(3,p.getUniqueId().toString());i.setString(4,"PENDING");i.setLong(5,System.currentTimeMillis());i.executeUpdate();return "二重承認を申請しました。";}catch(SQLException e){return "承認申請に失敗しました。";}}
    public String approve(Player p,String id){if(!p.isOp())return "管理者権限が必要です。";try(PreparedStatement u=db.connection().prepareStatement("UPDATE transaction_approvals SET approver=?,status='APPROVED',approved_at=? WHERE id=? AND status='PENDING' AND requester<>?")){u.setString(1,p.getUniqueId().toString());u.setLong(2,System.currentTimeMillis());u.setString(3,id);u.setString(4,p.getUniqueId().toString());return u.executeUpdate()==1?"承認しました。":"承認対象がないか、申請者と承認者が同一です。";}catch(SQLException e){return "承認に失敗しました。";}}
    public String setRelation(Player p,String source,String target,String relation,String note){if(!canManage(p,source))return "管理者権限が必要です。";if(!RELATIONS.contains(relation))return "関係は 良・普・嫌・同・提・子・親 のいずれかです。";try(PreparedStatement s=db.connection().prepareStatement("INSERT INTO company_relations VALUES(?,?,?,?,?) ON CONFLICT(source_company,target_company) DO UPDATE SET relation=excluded.relation,note=excluded.note,updated_at=excluded.updated_at")){s.setString(1,source);s.setString(2,target);s.setString(3,relation);s.setString(4,note==null?"":note);s.setLong(5,System.currentTimeMillis());s.executeUpdate();return "企業関係を更新しました。";}catch(SQLException e){return "企業関係の更新に失敗しました。";}}
    public String calculateCredit(String company){try{int score=500;try(PreparedStatement q=db.connection().prepareStatement("SELECT listed FROM companies WHERE name=?")){q.setString(1,company);try(ResultSet r=q.executeQuery()){if(!r.next())return "企業が見つかりません。";if(r.getInt(1)!=0)score+=100;}}String grade=score>=800?"AAA":score>=700?"AA":score>=600?"A":score>=500?"BBB":score>=400?"BB":"B";try(PreparedStatement s=db.connection().prepareStatement("INSERT INTO company_credit_scores VALUES((SELECT id FROM companies WHERE name=?),?,?,?,?) ON CONFLICT(company_id) DO UPDATE SET score=excluded.score,grade=excluded.grade,factors=excluded.factors,calculated_at=excluded.calculated_at")){s.setString(1,company);s.setInt(2,score);s.setString(3,grade);s.setString(4,"上場状態と基本運用履歴による基礎スコア");s.setLong(5,System.currentTimeMillis());s.executeUpdate();}return company+" 信用スコア="+score+" 格付け="+grade;}catch(SQLException e){return "信用スコア計算に失敗しました。";}}
    public String employment(Player admin,String action,String company,String mcid,String role,double salary,long days){if(!canManage(admin,company))return "管理者権限が必要です。";if(days<1)return "契約期間はリアル日で1日以上です。";String player=resolveMcid(mcid);if(player==null)return "MCID（プレイヤー名）が見つかりません。";try{if(action.equalsIgnoreCase("add")){try(PreparedStatement s=db.connection().prepareStatement("INSERT INTO employment_contracts VALUES(?,?,?,?,?,?,?,?,?)")){s.setString(1,UUID.randomUUID().toString());s.setString(2,company);s.setString(3,player);s.setString(4,role);s.setDouble(5,salary);s.setString(6,"");s.setLong(7,System.currentTimeMillis());s.setLong(8,System.currentTimeMillis()+days*86400000L);s.setString(9,"OFFERED");s.executeUpdate();}return "雇用招待を作成しました。対象MCID="+mcid;}if(action.equalsIgnoreCase("hire")){return updateEmployment(player,company,"HIRED")?"雇用招待を採用しました。":"採用できる招待がありません。";}if(action.equalsIgnoreCase("fire")){return updateEmployment(player,company,"TERMINATED")?"雇用契約を終了しました。":"対象の雇用契約がありません。";}return "操作はadd、hire、fireのいずれかです。";}catch(SQLException e){return "雇用処理に失敗しました。";}}
    private boolean updateEmployment(String player,String company,String status)throws SQLException{try(PreparedStatement u=db.connection().prepareStatement("UPDATE employment_contracts SET status=? WHERE company_id=? AND player=? AND status IN ('OFFERED','HIRED')")){u.setString(1,status);u.setString(2,company);u.setString(3,player);return u.executeUpdate()>0;}}
    private String resolveMcid(String mcid){if(mcid==null||mcid.isBlank())return null;org.bukkit.entity.Player p=org.bukkit.Bukkit.getPlayerExact(mcid);return p==null?null:p.getUniqueId().toString();}
    public String benefit(Player p,String action,String company,String item,String details){if(!canManage(p,company))return "管理者権限が必要です。";try{if(action.equalsIgnoreCase("add")){try(PreparedStatement s=db.connection().prepareStatement("INSERT INTO benefit_plans(id,company_id,name,details,cost,enabled) VALUES(?,?,?,?,0,1)")){s.setString(1,UUID.randomUUID().toString());s.setString(2,company);s.setString(3,item);s.setString(4,details);s.executeUpdate();}return "福利厚生を追加しました。";}if(action.equalsIgnoreCase("remove")){try(PreparedStatement s=db.connection().prepareStatement("UPDATE benefit_plans SET enabled=0 WHERE company_id=? AND name=? AND enabled=1")){s.setString(1,company);s.setString(2,item);return s.executeUpdate()>0?"福利厚生を削除しました。":"福利厚生が見つかりません。";}}return "操作はaddまたはremoveです。";}catch(SQLException e){return "福利厚生処理に失敗しました。";}}
    public String createInvoice(Player p,String seller,String buyer,double amount,long days){if(!canManage(p,seller)||amount<=0||days<1)return "企業権限、正しい金額、1日以上の期限が必要です。";try(PreparedStatement s=db.connection().prepareStatement("INSERT INTO invoices VALUES(?,?,?,?,?,?,?,?,NULL)")){s.setString(1,UUID.randomUUID().toString());s.setString(2,null);s.setString(3,seller);s.setString(4,buyer);s.setDouble(5,amount);s.setLong(6,System.currentTimeMillis()+days*86400000L);s.setString(7,"ISSUED");s.setLong(8,System.currentTimeMillis());s.executeUpdate();return "企業間請求書を発行しました。支払期限まで残り="+days+"日";}catch(SQLException e){return "請求書発行に失敗しました。";}}
    public String companyInfo(String company){try(PreparedStatement q=db.connection().prepareStatement("SELECT id,owner,listed,total_shares,share_price FROM companies WHERE name=?")){q.setString(1,company);try(ResultSet r=q.executeQuery()){if(!r.next())return "企業が見つかりません。";String status="ACTIVE";try(PreparedStatement s=db.connection().prepareStatement("SELECT status FROM company_status WHERE company_id=?")){s.setString(1,r.getString(1));try(ResultSet z=s.executeQuery()){if(z.next())status=z.getString(1);}}return "企業="+company+" 状態="+status+" 所有者MCID="+r.getString(2)+" 上場="+(r.getInt(3)!=0)+" 株式="+r.getLong(4)+" 株価="+r.getLong(5);}}catch(SQLException e){return "企業情報を取得できません。";}}
    public String closeCompany(Player p,String company,String reason){if(!canManage(p,company))return "対象企業の社長または社長以上の権限が必要です。";try{String id;try(PreparedStatement q=db.connection().prepareStatement("SELECT id FROM companies WHERE name=?")){q.setString(1,company);try(ResultSet r=q.executeQuery()){if(!r.next())return "企業が見つかりません。";id=r.getString(1);}}try(PreparedStatement q=db.connection().prepareStatement("SELECT COUNT(*) FROM invoices WHERE (issuer_company=? OR recipient_company=?) AND status IN ('ISSUED','OVERDUE')")){q.setString(1,company);q.setString(2,company);try(ResultSet r=q.executeQuery()){r.next();if(r.getLong(1)>0)return "未決済請求書があるため閉業できません。";}}try(PreparedStatement u=db.connection().prepareStatement("UPDATE companies SET listed=0 WHERE id=?")){u.setString(1,id);u.executeUpdate();}try(PreparedStatement s=db.connection().prepareStatement("INSERT INTO company_status(company_id,status,reason,closed_at) VALUES(?,?,?,?) ON CONFLICT(company_id) DO UPDATE SET status=excluded.status,reason=excluded.reason,closed_at=excluded.closed_at")){s.setString(1,id);s.setString(2,"CLOSED");s.setString(3,reason==null?"":reason);s.setLong(4,System.currentTimeMillis());s.executeUpdate();}return "企業を閉業しました。";}catch(SQLException e){return "閉業処理に失敗しました。";}}
}
