package jp.alticeworks.townymarket.service;

import jp.alticeworks.townymarket.storage.Database;
import org.bukkit.Bukkit;
import org.bukkit.entity.Player;
import java.sql.*;
import java.util.*;

public final class FinanceFeatures {
    private final Database db; private final MarketService market;
    public FinanceFeatures(Database db,MarketService market){this.db=db;this.market=market;}
    public double effectiveLoanRate(String nation){try{double policy=0;String rating="BBB";try(PreparedStatement q=db.connection().prepareStatement("SELECT policy_rate,credit_rating FROM nation_finance WHERE nation=?")){q.setString(1,nation);try(ResultSet r=q.executeQuery()){if(r.next()){policy=r.getDouble(1);rating=r.getString(2);}}}double spread=switch(rating==null?"BBB":rating.toUpperCase()){case "AAA"->1.0;case "AA"->1.5;case "A"->2.0;case "BBB"->3.0;case "BB"->5.0;case "B"->8.0;default->12.0;};return policy+spread;}catch(SQLException e){return 15.0;}}
    public String rateExplanation(String nation){double r=effectiveLoanRate(nation);return "国="+nation+" 融資金利="+r+"%（政策金利＋信用格付けスプレッド）";}
    public String createMeeting(Player admin,String company,String title,String description,long closesAt){if(!admin.isOp())return "管理者権限が必要です。";try{String id=null;try(PreparedStatement q=db.connection().prepareStatement("SELECT id FROM companies WHERE name=?")){q.setString(1,company);try(ResultSet r=q.executeQuery()){if(!r.next())return "企業が見つかりません。";id=r.getString(1);}}try(PreparedStatement i=db.connection().prepareStatement("INSERT INTO shareholder_meetings VALUES(?,?,?,?,?,?,?)")){i.setString(1,UUID.randomUUID().toString());i.setString(2,id);i.setString(3,title);i.setString(4,description);i.setLong(5,closesAt);i.setLong(6,System.currentTimeMillis());i.setString(7,"OPEN");i.executeUpdate();}return "株主総会議案を作成しました。";}catch(SQLException e){return "議案作成に失敗しました。";}}
    public String configureAutoDividend(Player admin,String company,double amount,long intervalSeconds){if(!admin.isOp())return "管理者権限が必要です。";if(amount<=0||intervalSeconds<60)return "配当額は正数、間隔は60秒以上にしてください。";try{String id=null;try(PreparedStatement q=db.connection().prepareStatement("SELECT id FROM companies WHERE name=? AND listed=1")){q.setString(1,company);try(ResultSet r=q.executeQuery()){if(!r.next())return "上場企業が見つかりません。";id=r.getString(1);}}try(PreparedStatement i=db.connection().prepareStatement("INSERT INTO auto_dividend_rules(company_id,interval_seconds,amount,next_run,enabled,updated_by) VALUES(?,?,?,?,1,?) ON CONFLICT(company_id) DO UPDATE SET interval_seconds=excluded.interval_seconds,amount=excluded.amount,next_run=excluded.next_run,enabled=1,updated_by=excluded.updated_by")){i.setString(1,id);i.setLong(2,intervalSeconds);i.setDouble(3,amount);i.setLong(4,System.currentTimeMillis()+intervalSeconds*1000L);i.setString(5,admin.getUniqueId().toString());i.executeUpdate();}return "自動配当を設定しました。";}catch(SQLException e){return "自動配当設定に失敗しました。";}}
    public int runDueAutoDividends(){int done=0;long now=System.currentTimeMillis();try(PreparedStatement q=db.connection().prepareStatement("SELECT c.name,c.owner,r.amount,r.interval_seconds FROM auto_dividend_rules r JOIN companies c ON c.id=r.company_id WHERE r.enabled=1 AND r.next_run<=?")){q.setLong(1,now);try(ResultSet r=q.executeQuery()){while(r.next()){Player owner=Bukkit.getPlayer(UUID.fromString(r.getString(2)));if(owner==null||!owner.isOnline())continue;String result=market.payDividend(owner,r.getString(1),r.getDouble(3));if(result.startsWith("配当")){try(PreparedStatement u=db.connection().prepareStatement("UPDATE auto_dividend_rules SET next_run=? WHERE company_id=(SELECT id FROM companies WHERE name=?)")){u.setLong(1,now+r.getLong(4)*1000L);u.setString(2,r.getString(1));u.executeUpdate();}done++;}}}}catch(Exception ignored){}return done;}
}
