package jp.alticeworks.townymarket.service;

import jp.alticeworks.townymarket.storage.Database;
import org.bukkit.entity.Player;
import java.sql.*;
import java.util.UUID;

/** Internal money ledger. All amounts are non-negative decimal values and every movement has a unique tx key. */
public final class FundsLedger {
    private final Database db;
    public FundsLedger(Database db){this.db=db;}
    public String balance(Player p,String currency){try{String id=account(p.getUniqueId().toString(),"PLAYER",currency);try(PreparedStatement q=db.connection().prepareStatement("SELECT available,reserved FROM fund_accounts WHERE account_id=?")){q.setString(1,id);try(ResultSet r=q.executeQuery()){if(!r.next())return currency+" 残高=0 予約=0";return currency+" 残高="+r.getDouble(1)+" 予約="+r.getDouble(2);}}}catch(SQLException e){return "残高取得に失敗しました。";}}
    public String reserve(Player p,double amount,String currency,String reference){if(amount<=0||reference==null||reference.isBlank())return "金額と参照IDが不正です。";try{Connection c=db.connection();c.setAutoCommit(false);String a=account(p.getUniqueId().toString(),"PLAYER",currency);try(PreparedStatement u=c.prepareStatement("UPDATE fund_accounts SET available=available-?,reserved=reserved+?,updated_at=? WHERE account_id=? AND available>=?")){u.setDouble(1,amount);u.setDouble(2,amount);u.setLong(3,System.currentTimeMillis());u.setString(4,a);u.setDouble(5,amount);if(u.executeUpdate()!=1){c.rollback();return "利用可能残高が不足しています。";}}try(PreparedStatement i=c.prepareStatement("INSERT INTO fund_reservations(id,account_id,currency,amount,reference_id,status,created_at) VALUES(?,?,?,?,?,'ACTIVE',?)")){i.setString(1,UUID.randomUUID().toString());i.setString(2,a);i.setString(3,currency);i.setDouble(4,amount);i.setString(5,reference);i.setLong(6,System.currentTimeMillis());i.executeUpdate();}c.commit();return "資金を予約しました。";}catch(Exception e){try{db.connection().rollback();}catch(SQLException ignored){}return "資金予約に失敗しました。";}finally{try{db.connection().setAutoCommit(true);}catch(SQLException ignored){}}}
    public String transfer(Player from,Player to,double amount,String currency,String txKey,String memo){if(amount<=0||txKey==null||txKey.isBlank())return "金額または取引キーが不正です。";try{Connection c=db.connection();c.setAutoCommit(false);String a=account(from.getUniqueId().toString(),"PLAYER",currency),b=account(to.getUniqueId().toString(),"PLAYER",currency);try(PreparedStatement q=c.prepareStatement("SELECT id FROM fund_journal WHERE tx_key=?")){q.setString(1,txKey);try(ResultSet r=q.executeQuery()){if(r.next()){c.rollback();return "この取引は既に処理済みです。";}}}try(PreparedStatement u=c.prepareStatement("UPDATE fund_accounts SET available=available-?,updated_at=? WHERE account_id=? AND available>=?")){u.setDouble(1,amount);u.setLong(2,System.currentTimeMillis());u.setString(3,a);u.setDouble(4,amount);if(u.executeUpdate()!=1){c.rollback();return "送金元の残高が不足しています。";}}try(PreparedStatement u=c.prepareStatement("UPDATE fund_accounts SET available=available+?,updated_at=? WHERE account_id=?")){u.setDouble(1,amount);u.setLong(2,System.currentTimeMillis());u.setString(3,b);u.executeUpdate();}try(PreparedStatement i=c.prepareStatement("INSERT INTO fund_journal(tx_key,debit_account,credit_account,currency,amount,fee,memo,created_at) VALUES(?,?,?,?,?,0,?,?)")){i.setString(1,txKey);i.setString(2,a);i.setString(3,b);i.setString(4,currency);i.setDouble(5,amount);i.setString(6,memo==null?"":memo);i.setLong(7,System.currentTimeMillis());i.executeUpdate();}c.commit();return "送金しました。";}catch(Exception e){try{db.connection().rollback();}catch(SQLException ignored){}return "送金に失敗しました。";}finally{try{db.connection().setAutoCommit(true);}catch(SQLException ignored){}}}
    private String account(String owner,String kind,String currency)throws SQLException{String id=kind+":"+owner+":"+currency.toUpperCase();try(PreparedStatement i=db.connection().prepareStatement("INSERT OR IGNORE INTO fund_accounts(account_id,owner,owner_kind,currency,available,reserved,updated_at) VALUES(?,?,?,?,0,0,?)")){i.setString(1,id);i.setString(2,owner);i.setString(3,kind);i.setString(4,currency.toUpperCase());i.setLong(5,System.currentTimeMillis());i.executeUpdate();}return id;}
}
