package jp.alticeworks.townymarket.service;

import jp.alticeworks.townymarket.storage.Database;
import jp.alticeworks.townymarket.towny.TownyHook;
import net.milkbowl.vault.economy.Economy;
import org.bukkit.entity.Player;
import java.sql.*;
import java.util.*;

public final class MarketService {
    public static final long LISTING_FEE=50000, FOREIGN_FEE=100000, CRYPTO_FEE=10000;
    private final Database db; private final Economy economy; private final TownyHook towny;
    public MarketService(Database db, Economy economy, TownyHook towny){this.db=db;this.economy=economy;this.towny=towny;}
    public boolean charge(Player p,double amount){return economy!=null&&economy.has(p,amount)&&economy.withdrawPlayer(p,amount).transactionSuccess();}
    public String createCompany(Player p,String name,String desc,long shares,long price){
        if(shares<1||price<1||name.length()<2||name.length()>32)return "入力値が不正です。";
        try { Connection c=db.connection(); c.setAutoCommit(false); String id=UUID.randomUUID().toString();
            try(PreparedStatement s=c.prepareStatement("INSERT INTO companies VALUES(?,?,?,?,0,?,?)")){s.setString(1,id);s.setString(2,p.getUniqueId().toString());s.setString(3,name);s.setString(4,desc);s.setLong(5,shares);s.setLong(6,price);s.executeUpdate();}
            try(PreparedStatement h=c.prepareStatement("INSERT INTO holdings(player,asset,kind,amount) VALUES(?,?,?,?)")){h.setString(1,p.getUniqueId().toString());h.setString(2,id);h.setString(3,"STOCK");h.setLong(4,shares);h.executeUpdate();}
            c.commit(); c.setAutoCommit(true); return "企業を作成しました。発行株式は所有者に割り当て済みです。上場には /tm list "+name+" を使用してください。";
        } catch(SQLException e){try{db.connection().rollback();db.connection().setAutoCommit(true);}catch(SQLException ignored){}return "企業名が既に存在します。";}
    }
    public String listCompany(Player p,String name){if(!charge(p,LISTING_FEE))return "所持金が不足しています。";try(PreparedStatement s=db.connection().prepareStatement("UPDATE companies SET listed=1 WHERE name=? AND owner=?")){s.setString(1,name);s.setString(2,p.getUniqueId().toString());if(s.executeUpdate()==0){economy.depositPlayer(p,LISTING_FEE);return "自分の企業が見つかりません。";}return "企業を上場しました。";}catch(SQLException e){return "処理に失敗しました。";}}
    public String issueForeign(Player p,String symbol,long supply,long price){String nation=towny.nationOf(p);if(nation==null||!towny.isKing(p,nation))return "Townyの国王のみ発行できます。";if(supply<1||price<1)return "供給量と価格は1以上にしてください。";if(!charge(p,FOREIGN_FEE))return "所持金が不足しています。";try(PreparedStatement s=db.connection().prepareStatement("INSERT INTO nation_currencies VALUES(?,?,?,?,?)")){s.setString(1,nation);s.setString(2,p.getUniqueId().toString());s.setString(3,symbol.toUpperCase());s.setLong(4,supply);s.setLong(5,price);s.executeUpdate();return "国の外資を発行しました: "+symbol;}catch(SQLException e){economy.depositPlayer(p,FOREIGN_FEE);return "その国またはシンボルは既に存在します。";}}
    public String createCrypto(Player p,String name,String symbol,long supply,long price){if(supply<1||price<1)return "供給量と開始値は1以上にしてください。";if(!charge(p,CRYPTO_FEE))return "所持金が不足しています。";try(PreparedStatement s=db.connection().prepareStatement("INSERT INTO cryptos VALUES(?,?,?,?,?,?)")){s.setString(1,UUID.randomUUID().toString());s.setString(2,p.getUniqueId().toString());s.setString(3,name);s.setString(4,symbol.toUpperCase());s.setLong(5,supply);s.setLong(6,price);s.executeUpdate();changeCrypto(p.getUniqueId(),symbol.toUpperCase(),supply);return "暗号資産を作成しました。初期供給量を作成者へ付与しました。";}catch(SQLException e){economy.depositPlayer(p,CRYPTO_FEE);return "名前またはシンボルが既に存在します。";}}
    public String mine(Player p,String symbol){
        try { long now=System.currentTimeMillis(); long cooldown=60000; long last=0; try(PreparedStatement q=db.connection().prepareStatement("SELECT last_mined FROM mining_stats WHERE player=? AND symbol=?")){q.setString(1,p.getUniqueId().toString());q.setString(2,symbol.toUpperCase());try(ResultSet r=q.executeQuery()){if(r.next())last=r.getLong(1);}}
            if(now-last<cooldown)return "マイニング待機中です。残り"+((cooldown-(now-last))/1000)+"秒"; long reward=1;
            try(PreparedStatement q=db.connection().prepareStatement("SELECT supply FROM cryptos WHERE symbol=?")){q.setString(1,symbol.toUpperCase());try(ResultSet r=q.executeQuery()){if(!r.next())return "暗号資産が見つかりません。";long supply=r.getLong(1);long difficulty=Math.max(1,Math.min(1000000,supply/100));long epoch=now/cooldown;int score=Math.floorMod((p.getUniqueId().toString()+":"+symbol.toUpperCase()+":"+epoch).hashCode(),1000000);if(score%difficulty>0)return "採掘失敗: 難易度="+difficulty+" スコア="+score;reward=Math.max(1,Math.min(100,supply/1000));}}
            changeCrypto(p.getUniqueId(),symbol.toUpperCase(),reward);try(PreparedStatement u=db.connection().prepareStatement("INSERT INTO mining_stats(player,symbol,last_mined,total_mined) VALUES(?,?,?,?) ON CONFLICT(player,symbol) DO UPDATE SET last_mined=excluded.last_mined,total_mined=total_mined+excluded.total_mined")){u.setString(1,p.getUniqueId().toString());u.setString(2,symbol.toUpperCase());u.setLong(3,now);u.setLong(4,reward);u.executeUpdate();}return "マイニング成功: "+reward+" "+symbol;
        }catch(SQLException e){return "マイニングに失敗しました。";}
    }
    public String stake(Player p,String symbol,long amount){if(amount<1)return "ステーキング数量は1以上です。";try{if(!changeCrypto(p.getUniqueId(),symbol.toUpperCase(),-amount))return "暗号資産残高が不足しています。";long now=System.currentTimeMillis();try(PreparedStatement u=db.connection().prepareStatement("INSERT INTO crypto_stakes(player,symbol,amount,started_at,last_reward) VALUES(?,?,?,?,?) ON CONFLICT(player,symbol) DO UPDATE SET amount=amount+excluded.amount")){u.setString(1,p.getUniqueId().toString());u.setString(2,symbol.toUpperCase());u.setLong(3,amount);u.setLong(4,now);u.setLong(5,now);u.executeUpdate();}return "ステーキング開始: "+amount+" "+symbol;}catch(SQLException e){return "ステーキングに失敗しました。";}}
    public String unstake(Player p,String symbol){try{long amount=0,started=0;try(PreparedStatement q=db.connection().prepareStatement("SELECT amount,started_at FROM crypto_stakes WHERE player=? AND symbol=?")){q.setString(1,p.getUniqueId().toString());q.setString(2,symbol.toUpperCase());try(ResultSet r=q.executeQuery()){if(!r.next())return "ステーキング残高がありません。";amount=r.getLong(1);started=r.getLong(2);}}long elapsedSeconds=Math.max(0,(System.currentTimeMillis()-started)/1000);long reward=Math.max(0,amount*12*elapsedSeconds/(100*86400));changeCrypto(p.getUniqueId(),symbol.toUpperCase(),amount+reward);try(PreparedStatement d=db.connection().prepareStatement("DELETE FROM crypto_stakes WHERE player=? AND symbol=?")){d.setString(1,p.getUniqueId().toString());d.setString(2,symbol.toUpperCase());d.executeUpdate();}return "ステーキング解除: 元本="+amount+" 報酬="+reward+" 経過秒="+elapsedSeconds+" APR=12%";}catch(SQLException e){return "ステーキング解除に失敗しました。";}}
    public String cryptoInfo(Player p,String symbol){try(PreparedStatement q=db.connection().prepareStatement("SELECT amount FROM crypto_balances WHERE player=? AND symbol=?")){q.setString(1,p.getUniqueId().toString());q.setString(2,symbol.toUpperCase());try(ResultSet r=q.executeQuery()){long balance=r.next()?r.getLong(1):0;return symbol.toUpperCase()+" 残高="+balance;}}catch(SQLException e){return "情報取得に失敗しました。";}}
    private boolean changeCrypto(UUID player,String symbol,long delta)throws SQLException{try(PreparedStatement q=db.connection().prepareStatement("SELECT amount FROM crypto_balances WHERE player=? AND symbol=?")){q.setString(1,player.toString());q.setString(2,symbol);try(ResultSet r=q.executeQuery()){long old=r.next()?r.getLong(1):0;if(old+delta<0)return false;try(PreparedStatement u=db.connection().prepareStatement("INSERT INTO crypto_balances(player,symbol,amount) VALUES(?,?,?) ON CONFLICT(player,symbol) DO UPDATE SET amount=excluded.amount")){u.setString(1,player.toString());u.setString(2,symbol);u.setLong(3,old+delta);u.executeUpdate();return true;}}}}
    public boolean canManageTax(Player p){String nation=towny.nationOf(p);return nation!=null&&towny.isKing(p,nation);}
    public String adjustTax(Player p,String type,double delta){String nation=towny.nationOf(p);if(nation==null||!towny.isKing(p,nation))return "Townyの国王のみ設定できます。";try{ensureTax(nation);try(PreparedStatement q=db.connection().prepareStatement("SELECT "+type+"_rate FROM nation_tax WHERE nation=?")){q.setString(1,nation);try(ResultSet r=q.executeQuery()){if(!r.next())return "税率を取得できません。";return setTax(p,type,r.getDouble(1)+delta);}}}catch(SQLException e){return "税率調整に失敗しました。";}}
    public String setTax(Player p,String type,double rate){if(rate<0||rate>100)return "税率は0〜100%で指定してください。";String nation=towny.nationOf(p);if(nation==null||!towny.isKing(p,nation))return "Townyの国王のみ設定できます。";type=type.toLowerCase();if(!Set.of("foreign","stock","crypto").contains(type))return "税種別はforeign、stock、cryptoです。";try{ensureTax(nation);String col=type+"_rate";try(PreparedStatement s=db.connection().prepareStatement("UPDATE nation_tax SET "+col+"=? WHERE nation=?")){s.setDouble(1,rate);s.setString(2,nation);s.executeUpdate();}return nation+"の"+type+"税率を"+rate+"%に設定しました。";}catch(SQLException e){return "税率設定に失敗しました。";}}
    public String taxInfo(Player p){String nation=towny.nationOf(p);if(nation==null)return "Townyの国に所属していません。";try{ensureTax(nation);try(PreparedStatement s=db.connection().prepareStatement("SELECT foreign_rate,stock_rate,crypto_rate,treasury FROM nation_tax WHERE nation=?")){s.setString(1,nation);try(ResultSet r=s.executeQuery()){r.next();return nation+" 税率: 外資="+r.getDouble(1)+"% 株="+r.getDouble(2)+"% 暗号="+r.getDouble(3)+"% 国庫="+r.getDouble(4);}}}catch(SQLException e){return "税制情報を取得できません。";}}
    private void ensureTax(String nation)throws SQLException{try(PreparedStatement s=db.connection().prepareStatement("INSERT OR IGNORE INTO nation_tax(nation) VALUES(?)")){s.setString(1,nation);s.executeUpdate();}}
    private double taxRate(String nation,String type)throws SQLException{if(nation==null)return 0;ensureTax(nation);try(PreparedStatement s=db.connection().prepareStatement("SELECT "+type+"_rate FROM nation_tax WHERE nation=?")){s.setString(1,nation);try(ResultSet r=s.executeQuery()){return r.next()?r.getDouble(1):0;}}}
    public String setNisa(Player p,double limit){String nation=towny.nationOf(p);if(nation==null||!towny.isKing(p,nation))return "自国の国王のみNISAを設定できます。";if(limit<0)return "限度額は0以上です。";try(PreparedStatement s=db.connection().prepareStatement("INSERT INTO nation_nisa(nation,limit_amount,used_amount,updated_at) VALUES(?,?,0,?) ON CONFLICT(nation) DO UPDATE SET limit_amount=excluded.limit_amount,used_amount=CASE WHEN excluded.limit_amount=0 THEN 0 ELSE MIN(used_amount,excluded.limit_amount) END,updated_at=excluded.updated_at")){s.setString(1,nation);s.setDouble(2,limit);s.setLong(3,System.currentTimeMillis());s.executeUpdate();return nation+"のNISA限度額を"+limit+"に設定しました。";}catch(SQLException e){return "NISA設定に失敗しました。";}}
    private double useNisa(String nation,String player,String assetType,double gross)throws SQLException{if(nation==null||gross<=0)return 0;try(PreparedStatement q=db.connection().prepareStatement("SELECT limit_amount,used_amount FROM nation_nisa WHERE nation=?")){q.setString(1,nation);try(ResultSet r=q.executeQuery()){if(!r.next()||r.getDouble(1)<=0)return 0;double exempt=Math.min(gross,Math.max(0,r.getDouble(1)-r.getDouble(2)));if(exempt<=0)return 0;try(PreparedStatement u=db.connection().prepareStatement("UPDATE nation_nisa SET used_amount=used_amount+?,updated_at=? WHERE nation=?")){u.setDouble(1,exempt);u.setLong(2,System.currentTimeMillis());u.setString(3,nation);u.executeUpdate();}try(PreparedStatement l=db.connection().prepareStatement("INSERT INTO nisa_ledger(nation,player,asset_type,gross,exempt,taxable,tax,created_at) VALUES(?,?,?,?,?,?,?,?)")){l.setString(1,nation);l.setString(2,player);l.setString(3,assetType);l.setDouble(4,gross);l.setDouble(5,exempt);l.setDouble(6,gross-exempt);l.setDouble(7,0);l.setLong(8,System.currentTimeMillis());l.executeUpdate();}return exempt;}}}
    private void collectTax(String nation,String type,String payer,double gross,double tax)throws SQLException{if(nation==null||tax<=0)return;ensureTax(nation);try(PreparedStatement u=db.connection().prepareStatement("UPDATE nation_tax SET treasury=treasury+? WHERE nation=?")){u.setDouble(1,tax);u.setString(2,nation);u.executeUpdate();}try(PreparedStatement l=db.connection().prepareStatement("INSERT INTO tax_ledger(nation,asset_type,payer,gross,tax,created_at) VALUES(?,?,?,?,?,?)")){l.setString(1,nation);l.setString(2,type);l.setString(3,payer);l.setDouble(4,gross);l.setDouble(5,tax);l.setLong(6,System.currentTimeMillis());l.executeUpdate();}}
    public String payDividend(Player p,String company,double total){if(total<=0)return "配当総額は0より大きくしてください。";try{String id=null;try(PreparedStatement q=db.connection().prepareStatement("SELECT id FROM companies WHERE name=? AND owner=? AND listed=1")){q.setString(1,company);q.setString(2,p.getUniqueId().toString());try(ResultSet r=q.executeQuery()){if(!r.next())return "自分の上場企業が見つかりません。";id=r.getString(1);}}if(!charge(p,total))return "配当原資が不足しています。";String dividend=UUID.randomUUID().toString();try(PreparedStatement d=db.connection().prepareStatement("INSERT INTO dividends VALUES(?,?,?,?,?,?)")){d.setString(1,dividend);d.setString(2,id);d.setString(3,p.getUniqueId().toString());d.setDouble(4,total);d.setDouble(5,total);d.setLong(6,System.currentTimeMillis());d.executeUpdate();}long shares=0;try(PreparedStatement q=db.connection().prepareStatement("SELECT COALESCE(SUM(amount),0) FROM holdings WHERE asset=? AND kind='STOCK'")){q.setString(1,id);try(ResultSet r=q.executeQuery()){r.next();shares=r.getLong(1);}}if(shares<1){economy.depositPlayer(p,total);return "保有株主がいないため配当を中止しました。";}double per=total/shares;try(PreparedStatement pu=db.connection().prepareStatement("UPDATE dividends SET per_share=? WHERE id=?")){pu.setDouble(1,per);pu.setString(2,dividend);pu.executeUpdate();}try(PreparedStatement q=db.connection().prepareStatement("SELECT player,amount FROM holdings WHERE asset=? AND kind='STOCK' AND amount>0")){q.setString(1,id);try(ResultSet r=q.executeQuery()){while(r.next()){String holder=r.getString(1);long held=r.getLong(2);double gross=per*held;String nation=towny.nationOf(org.bukkit.Bukkit.getPlayer(UUID.fromString(holder)));double exempt=useNisa(nation,holder,"stock",gross);double taxable=Math.max(0,gross-exempt);double tax=taxable*taxRate(nation,"stock")/100.0;double net=Math.max(0,gross-tax);try(PreparedStatement c=db.connection().prepareStatement("INSERT INTO dividend_entitlements(dividend_id,player,shares,gross,tax,net,claimed) VALUES(?,?,?,?,?,?,0)")){c.setString(1,dividend);c.setString(2,holder);c.setLong(3,held);c.setDouble(4,gross);c.setDouble(5,tax);c.setDouble(6,net);c.executeUpdate();}}}}return "配当を配布しました。総額="+total+" 1株配当="+per;}catch(SQLException e){return "配当処理に失敗しました。";}}
    public String claimDividend(Player p,String dividendId){try{Connection c=db.connection();c.setAutoCommit(false);double net,tax;try(PreparedStatement q=c.prepareStatement("SELECT net,tax,claimed FROM dividend_entitlements WHERE dividend_id=? AND player=?")){q.setString(1,dividendId);q.setString(2,p.getUniqueId().toString());try(ResultSet r=q.executeQuery()){if(!r.next()){c.rollback();return "未受領の配当が見つかりません。";}if(r.getInt(3)!=0){c.rollback();return "この配当は既に受領済みです。";}net=r.getDouble(1);tax=r.getDouble(2);}}if(economy==null||!economy.depositPlayer(p,net).transactionSuccess()){c.rollback();return "配当の送金に失敗しました。";}try(PreparedStatement u=c.prepareStatement("UPDATE dividend_entitlements SET claimed=1,claimed_at=? WHERE dividend_id=? AND player=? AND claimed=0")){u.setLong(1,System.currentTimeMillis());u.setString(2,dividendId);u.setString(3,p.getUniqueId().toString());if(u.executeUpdate()!=1){c.rollback();return "配当状態を更新できません。";}}String nation=towny.nationOf(p);collectTax(nation,"stock",p.getUniqueId().toString(),net+tax,tax);c.commit();return "配当を受領しました。手取り="+net+" 税額="+tax;}catch(Exception e){try{db.connection().rollback();}catch(SQLException ignored){}return "配当受領に失敗しました。";}finally{try{db.connection().setAutoCommit(true);}catch(SQLException ignored){}}}
    public List<String> cryptoList(){List<String> out=new ArrayList<>();try(Statement s=db.connection().createStatement();ResultSet r=s.executeQuery("SELECT symbol,price,supply FROM cryptos ORDER BY symbol")){while(r.next())out.add(r.getString(1)+" / 価格="+r.getLong(2)+" / 供給="+r.getLong(3));}catch(SQLException ignored){}return out;}
    public String placeOrder(Player p,String symbol,String side,String type,long quantity,long limitPrice){
        if(economy==null)return "Vault経済が利用できません。";if(quantity<1||limitPrice<0)return "数量は1以上、価格は0以上です。";side=side.toUpperCase();type=type.toUpperCase();if(!side.equals("BUY")&&!side.equals("SELL"))return "売買区分はBUYまたはSELLです。";if(!type.equals("LIMIT")&&!type.equals("MARKET"))return "注文種別はLIMITまたはMARKETです。";if(type.equals("LIMIT")&&limitPrice<1)return "指値は1以上です。";
        Connection c=db.connection();try{c.setAutoCommit(false);String id;long last;try(PreparedStatement q=c.prepareStatement("SELECT id,share_price FROM companies WHERE name=? AND listed=1")){q.setString(1,symbol);try(ResultSet r=q.executeQuery()){if(!r.next()){c.rollback();return "上場株式が見つかりません。";}id=r.getString(1);last=r.getLong(2);}}
            if(side.equals("SELL")&&!changeHolding(p,id,"STOCK",-quantity)){c.rollback();return "保有株数が不足しています。";}
            String orderId=UUID.randomUUID().toString();try(PreparedStatement s=c.prepareStatement("INSERT INTO orders(id,asset,owner,side,type,price,quantity,remaining,status,created_at) VALUES(?,?,?,?,?,?,?,?,?,?)")){s.setString(1,orderId);s.setString(2,id);s.setString(3,p.getUniqueId().toString());s.setString(4,side);s.setString(5,type);s.setLong(6,limitPrice);s.setLong(7,quantity);s.setLong(8,quantity);s.setString(9,"OPEN");s.setLong(10,System.currentTimeMillis());s.executeUpdate();}
            long filled=match(c,id,orderId,last);c.commit();return "注文を受付: "+orderId+" / 約定 "+filled+"株";
        }catch(Exception e){try{c.rollback();}catch(SQLException ignored){}return "注文処理に失敗しました。";}finally{try{c.setAutoCommit(true);}catch(SQLException ignored){}}
    }
    private long match(Connection c,String asset,String incoming,long last)throws SQLException {
        long filled=0;
        try (PreparedStatement iq=c.prepareStatement("SELECT side,price,type,remaining,owner FROM orders WHERE id=?")) {
            iq.setString(1,incoming);
            try (ResultSet ir=iq.executeQuery()) {
                if(!ir.next()) return 0;
                String side=ir.getString("side"); String incomingType=ir.getString("type");
                long incomingPrice=ir.getLong("price"), remain=ir.getLong("remaining"); String owner=ir.getString("owner");
                String opposite=side.equals("BUY")?"SELL":"BUY";
                String predicate=incomingType.equals("MARKET")?"1=1":(side.equals("BUY")?"(type='MARKET' OR price<=?)":"(type='MARKET' OR price>=?)");
                String sort=side.equals("BUY")?"CASE WHEN type='LIMIT' THEN price ELSE 9223372036854775807 END ASC":"CASE WHEN type='LIMIT' THEN price ELSE 0 END DESC";
                String sql="SELECT id,price,remaining,owner FROM orders WHERE asset=? AND side=? AND status='OPEN' AND remaining>0 AND "+predicate+" ORDER BY "+sort+",created_at ASC";
                try(PreparedStatement oq=c.prepareStatement(sql)) {
                    oq.setString(1,asset); oq.setString(2,opposite); if(!incomingType.equals("MARKET")) oq.setLong(3,incomingPrice);
                    try(ResultSet r=oq.executeQuery()) {
                        while(remain>0&&r.next()) {
                            long qty=Math.min(remain,r.getLong("remaining")); long tradePrice=r.getLong("price")>0?r.getLong("price"):last; if(tradePrice<1)tradePrice=last;
                            long value=Math.multiplyExact(qty,tradePrice); String counterparty=r.getString("owner");
                            Player buyer=org.bukkit.Bukkit.getPlayer(UUID.fromString(side.equals("BUY")?owner:counterparty));
                            Player seller=org.bukkit.Bukkit.getPlayer(UUID.fromString(side.equals("BUY")?counterparty:owner));
                            if(buyer==null||seller==null) continue;
                            String nation=towny.nationOf(buyer); double tax=value*taxRate(nation,"stock")/100.0; double total=value+tax;
                            if(!economy.has(buyer,total)||!economy.withdrawPlayer(buyer,total).transactionSuccess()||!changeHoldingByUuid(buyer.getUniqueId(),asset,"STOCK",qty)) continue;
                            economy.depositPlayer(seller,value); collectTax(nation,"stock",buyer.getUniqueId().toString(),value,tax);
                            try(PreparedStatement u=c.prepareStatement("UPDATE orders SET remaining=remaining-?,status=CASE WHEN remaining-?=0 THEN 'FILLED' ELSE 'OPEN' END WHERE id=?")){u.setLong(1,qty);u.setLong(2,qty);u.setString(3,r.getString("id"));u.executeUpdate();}
                            remain-=qty; filled+=qty; last=adjustPrice(last,side,qty,tradePrice); recordTrade(c,asset,tradePrice,qty);
                        }
                    }
                }
                try(PreparedStatement u=c.prepareStatement("UPDATE orders SET remaining=?,status=CASE WHEN ?=0 THEN 'FILLED' ELSE 'OPEN' END WHERE id=?")){u.setLong(1,remain);u.setLong(2,remain);u.setString(3,incoming);u.executeUpdate();}
                updatePrice(c,asset,last);
            }
        }
        return filled;
    }
    private long adjustPrice(long old,String side,long qty,long trade){double pressure=Math.min(0.10,qty/10000.0);double next=side.equals("BUY")?trade*(1+pressure):trade*(1-pressure);return Math.max(1,Math.round(next));}
    private void recordTrade(Connection c,String asset,long price,long qty)throws SQLException{try(PreparedStatement s=c.prepareStatement("INSERT INTO trades(asset,price,quantity,executed_at) VALUES(?,?,?,?)")){s.setString(1,asset);s.setLong(2,price);s.setLong(3,qty);s.setLong(4,System.currentTimeMillis());s.executeUpdate();}}
    private void updatePrice(Connection c,String asset,long price)throws SQLException{try(PreparedStatement s=c.prepareStatement("UPDATE companies SET share_price=? WHERE id=?")){s.setLong(1,price);s.setString(2,asset);s.executeUpdate();}}
    private boolean changeHolding(Player p,String asset,String kind,long delta)throws SQLException{return changeHoldingByUuid(p.getUniqueId(),asset,kind,delta);}
    private boolean changeHoldingByUuid(UUID player,String asset,String kind,long delta)throws SQLException{try(PreparedStatement q=db.connection().prepareStatement("SELECT amount FROM holdings WHERE player=? AND asset=? AND kind=?")){q.setString(1,player.toString());q.setString(2,asset);q.setString(3,kind);try(ResultSet r=q.executeQuery()){long old=r.next()?r.getLong(1):0;if(old+delta<0)return false;try(PreparedStatement u=db.connection().prepareStatement("INSERT INTO holdings(player,asset,kind,amount) VALUES(?,?,?,?) ON CONFLICT(player,asset,kind) DO UPDATE SET amount=excluded.amount")){u.setString(1,player.toString());u.setString(2,asset);u.setString(3,kind);u.setLong(4,old+delta);u.executeUpdate();return true;}}}}
    public List<String> market(){List<String> out=new ArrayList<>();try(Statement s=db.connection().createStatement();ResultSet r=s.executeQuery("SELECT name,share_price FROM companies WHERE listed=1 ORDER BY name")){while(r.next())out.add("株式 "+r.getString(1)+" / 現在値="+r.getLong(2)+" / "+book(r.getString(1)));}catch(SQLException ignored){}return out;}
    private String book(String name){try(PreparedStatement s=db.connection().prepareStatement("SELECT side,COALESCE(SUM(remaining),0) FROM orders o JOIN companies c ON c.id=o.asset WHERE c.name=? AND o.status='OPEN' GROUP BY side")){s.setString(1,name);String b="買い板=0 売り板=0";try(ResultSet r=s.executeQuery()){long buy=0,sell=0;while(r.next()){if(r.getString(1).equals("BUY"))buy=r.getLong(2);else sell=r.getLong(2);}return "買い板="+buy+" 売り板="+sell;}}catch(SQLException e){return "買い板=0 売り板=0";}}
}
