package jp.alticeworks.townymarket.web;

import com.sun.net.httpserver.HttpExchange;
import com.sun.net.httpserver.HttpServer;
import jp.alticeworks.townymarket.service.MarketService;
import jp.alticeworks.townymarket.service.FinanceFeatures;
import jp.alticeworks.townymarket.storage.Database;
import jp.alticeworks.townymarket.towny.TownyHook;
import org.bukkit.Bukkit;
import org.bukkit.entity.Player;
import org.bukkit.plugin.java.JavaPlugin;
import java.io.*;
import java.net.*;
import java.nio.charset.StandardCharsets;
import java.sql.*;
import java.util.*;
import java.util.concurrent.*;

public final class WebConsoleServer {
    public static final String VERSION="0.1.0";
    private final JavaPlugin plugin; private final Database db; private final MarketService market; private final FinanceFeatures finance; private final TownyHook towny; private HttpServer server; private final Set<String> sessions=ConcurrentHashMap.newKeySet();
    public WebConsoleServer(JavaPlugin plugin,Database db,MarketService market,FinanceFeatures finance){this.plugin=plugin;this.db=db;this.market=market;this.finance=finance;this.towny=new TownyHook(plugin);}
    public void start(){if(!plugin.getConfig().getBoolean("webconsole.enabled",true))return;try{int port=plugin.getConfig().getInt("webconsole.port",2026);server=HttpServer.create(new InetSocketAddress(port),0);server.setExecutor(Executors.newCachedThreadPool(r->{Thread t=new Thread(r,"TM-WebConsole");t.setDaemon(true);return t;}));server.createContext("/",this::handle);server.start();plugin.getLogger().info("TM-WebConsole "+VERSION+" listening on port "+port);}catch(IOException e){plugin.getLogger().severe("TM-WebConsole failed to start: "+e.getMessage());}}
    public void stop(){if(server!=null){server.stop(0);server=null;}sessions.clear();}
    private void handle(HttpExchange x)throws IOException{try{String p=x.getRequestURI().getPath();if(p.equals("/api/login")){login(x);return;}if(p.startsWith("/api/")){api(x);return;}staticFile(x,p);}catch(Exception e){send(x,500,"application/json","{\"error\":\"internal error\"}");}}
    private void login(HttpExchange x)throws IOException{if(!x.getRequestMethod().equalsIgnoreCase("POST")){send(x,405,"application/json","{\"error\":\"method not allowed\"}");return;}String body=new String(x.getRequestBody().readAllBytes(),StandardCharsets.UTF_8);String password=field(body,"password");String expected=plugin.getConfig().getString("webconsole.password","");if(expected.isBlank()||!constantTime(password,expected)){send(x,401,"application/json","{\"error\":\"unauthorized\"}");return;}String token=UUID.randomUUID().toString();sessions.add(token);x.getResponseHeaders().add("Set-Cookie","tm_session="+token+"; HttpOnly; SameSite=Strict; Path=/");send(x,200,"application/json","{\"ok\":true,\"role\":\"admin\",\"version\":\""+VERSION+"\"}");}
    private boolean constantTime(String a,String b){return java.security.MessageDigest.isEqual(a.getBytes(StandardCharsets.UTF_8),b.getBytes(StandardCharsets.UTF_8));}
    private boolean auth(HttpExchange x){String c=x.getRequestHeaders().getFirst("Cookie");if(c==null)return false;for(String v:c.split(";")){String z=v.trim();if(z.startsWith("tm_session=")&&sessions.contains(z.substring(11)))return true;}return false;}
    private void api(HttpExchange x)throws IOException{if(!auth(x)){send(x,401,"application/json","{\"error\":\"login required\"}");return;}String p=x.getRequestURI().getPath();if(p.equals("/api/health")){send(x,200,"application/json","{\"ok\":true,\"version\":\""+VERSION+"\"}");return;}if(p.equals("/api/summary")){send(x,200,"application/json",summary());return;}if(p.equals("/api/me")){send(x,200,"application/json",identity(query(x,"mcid")));return;}if(p.equals("/api/market")){send(x,200,"application/json",marketJson(query(x,"mcid")));return;}if(p.equals("/api/tax")){send(x,200,"application/json",taxJson(query(x,"mcid")));return;}if(p.equals("/api/dividends")){send(x,200,"application/json",dividendsJson(query(x,"mcid")));return;}if(p.equals("/api/dividends/claim")){claimDividend(x);return;}if(p.equals("/api/meetings")){send(x,200,"application/json",meetingsJson(query(x,"mcid")));return;}if(p.equals("/api/meetings/vote")){voteMeeting(x);return;}if(p.equals("/api/order")){order(x);return;}if(p.equals("/api/admin/meeting")){adminMeeting(x);return;}if(p.equals("/api/admin/autodividend")){adminAutoDividend(x);return;}send(x,404,"application/json","{\"error\":\"not found\"}");}
    private String identity(String mcid){Player p=player(mcid);if(p==null)return "{\"error\":\"MCID must belong to an online player\"}";String nation=towny.nationOf(p);return "{\"mcid\":\""+esc(p.getUniqueId().toString())+"\",\"player\":\""+esc(p.getName())+"\",\"nation\":"+str(nation)+",\"towny\":"+towny.available()+"}";}
    private String marketJson(String mcid){Player p=player(mcid);if(p==null)return "{\"error\":\"MCID must belong to an online player\"}";String nation=towny.nationOf(p);StringBuilder b=new StringBuilder("{\"nation\":").append(str(nation)).append(",\"exchange\":").append(str(nation==null?"Global Exchange":nation+" National Exchange")).append(",\"stocks\":[");try(PreparedStatement q=db.connection().prepareStatement("SELECT name,share_price,total_shares FROM companies WHERE listed=1 ORDER BY name")){try(ResultSet r=q.executeQuery()){boolean first=true;while(r.next()){if(!first)b.append(',');first=false;b.append("{\"symbol\":").append(str(r.getString(1))).append(",\"price\":").append(r.getLong(2)).append(",\"shares\":").append(r.getLong(3)).append("}");}}}catch(SQLException e){return "{\"error\":\"database unavailable\"}";}return b.append("]}").toString();}
    private String taxJson(String mcid){Player p=player(mcid);if(p==null)return "{\"error\":\"MCID must belong to an online player\"}";String n=towny.nationOf(p);return "{\"nation\":"+str(n)+",\"message\":"+str(market.taxInfo(p))+"}";}
    private String dividendsJson(String mcid){Player p=player(mcid);if(p==null)return "{\"error\":\"MCID must belong to an online player\"}";StringBuilder b=new StringBuilder("{\"items\":[");try(PreparedStatement q=db.connection().prepareStatement("SELECT e.dividend_id,c.name,e.gross,e.tax,e.net,e.claimed,d.created_at FROM dividend_entitlements e JOIN dividends d ON d.id=e.dividend_id JOIN companies c ON c.id=d.company_id WHERE e.player=? ORDER BY d.created_at DESC")){q.setString(1,p.getUniqueId().toString());try(ResultSet r=q.executeQuery()){boolean first=true;while(r.next()){if(!first)b.append(',');first=false;b.append("{\"id\":").append(str(r.getString(1))).append(",\"company\":").append(str(r.getString(2))).append(",\"gross\":").append(r.getDouble(3)).append(",\"tax\":").append(r.getDouble(4)).append(",\"net\":").append(r.getDouble(5)).append(",\"claimed\":").append(r.getInt(6)!=0).append(",\"createdAt\":").append(r.getLong(7)).append("}");}}}catch(SQLException e){return "{\"error\":\"database unavailable\"}";}return b.append("]}").toString();}
    private void claimDividend(HttpExchange x)throws IOException{if(!x.getRequestMethod().equalsIgnoreCase("POST")){send(x,405,"application/json","{\"error\":\"POST required\"}");return;}try{String body=new String(x.getRequestBody().readAllBytes(),StandardCharsets.UTF_8);Player p=player(field(body,"mcid"));if(p==null){send(x,400,"application/json","{\"error\":\"MCID must belong to an online player\"}");return;}send(x,200,"application/json","{\"result\":"+str(market.claimDividend(p,field(body,"dividendId")))+"}");}catch(Exception e){send(x,400,"application/json","{\"error\":\"invalid request\"}");}}
    private String meetingsJson(String mcid){Player p=player(mcid);if(p==null)return "{\"error\":\"MCID must belong to an online player\"}";StringBuilder b=new StringBuilder("{\"items\":[");try(PreparedStatement q=db.connection().prepareStatement("SELECT m.id,c.name,m.title,m.description,m.closes_at,m.status,COALESCE(h.amount,0),CASE WHEN v.player IS NULL THEN 0 ELSE 1 END FROM shareholder_meetings m JOIN companies c ON c.id=m.company_id LEFT JOIN holdings h ON h.asset=m.company_id AND h.player=? AND h.kind='STOCK' LEFT JOIN meeting_votes v ON v.meeting_id=m.id AND v.player=? WHERE m.status='OPEN' ORDER BY m.closes_at")){q.setString(1,p.getUniqueId().toString());q.setString(2,p.getUniqueId().toString());try(ResultSet r=q.executeQuery()){boolean first=true;while(r.next()){if(!first)b.append(',');first=false;b.append("{\"id\":").append(str(r.getString(1))).append(",\"company\":").append(str(r.getString(2))).append(",\"title\":").append(str(r.getString(3))).append(",\"description\":").append(str(r.getString(4))).append(",\"closesAt\":").append(r.getLong(5)).append(",\"votingPower\":").append(r.getLong(7)).append(",\"voted\":").append(r.getInt(8)!=0).append("}");}}}catch(SQLException e){return "{\"error\":\"database unavailable\"}";}return b.append("]}").toString();}
    private void voteMeeting(HttpExchange x)throws IOException{if(!x.getRequestMethod().equalsIgnoreCase("POST")){send(x,405,"application/json","{\"error\":\"POST required\"}");return;}String body=new String(x.getRequestBody().readAllBytes(),StandardCharsets.UTF_8);Player p=player(field(body,"mcid"));if(p==null){send(x,400,"application/json","{\"error\":\"MCID must belong to an online player\"}");return;}String choice=field(body,"choice").toUpperCase();if(!Set.of("FOR","AGAINST","ABSTAIN").contains(choice)){send(x,400,"application/json","{\"error\":\"invalid choice\"}");return;}try(PreparedStatement q=db.connection().prepareStatement("SELECT h.amount FROM shareholder_meetings m JOIN holdings h ON h.asset=m.company_id AND h.player=? AND h.kind='STOCK' WHERE m.id=? AND m.status='OPEN' AND m.closes_at>?")){q.setString(1,p.getUniqueId().toString());q.setString(2,field(body,"meetingId"));q.setLong(3,System.currentTimeMillis());try(ResultSet r=q.executeQuery()){if(!r.next()||r.getLong(1)<=0){send(x,403,"application/json","{\"error\":\"voting right unavailable\"}");return;}long power=r.getLong(1);try(PreparedStatement i=db.connection().prepareStatement("INSERT INTO meeting_votes(meeting_id,player,choice,voting_power,voted_at) VALUES(?,?,?,?,?)")){i.setString(1,field(body,"meetingId"));i.setString(2,p.getUniqueId().toString());i.setString(3,choice);i.setLong(4,power);i.setLong(5,System.currentTimeMillis());i.executeUpdate();send(x,200,"application/json","{\"ok\":true,\"votingPower\":"+power+"}");}}}catch(SQLException e){send(x,409,"application/json","{\"error\":\"already voted or database error\"}");}}
    private void adminMeeting(HttpExchange x)throws IOException{if(!x.getRequestMethod().equalsIgnoreCase("POST")){send(x,405,"application/json","{\"error\":\"POST required\"}");return;}String b=new String(x.getRequestBody().readAllBytes(),StandardCharsets.UTF_8);Player p=player(field(b,"adminMcid"));if(p==null||!p.isOp()){send(x,403,"application/json","{\"error\":\"operator MCID required\"}");return;}String result=finance.createMeeting(p,field(b,"company"),field(b,"title"),field(b,"description"),System.currentTimeMillis()+Long.parseLong(field(b,"durationSeconds"))*1000L);send(x,200,"application/json","{\"result\":"+str(result)+"}");}
    private void adminAutoDividend(HttpExchange x)throws IOException{if(!x.getRequestMethod().equalsIgnoreCase("POST")){send(x,405,"application/json","{\"error\":\"POST required\"}");return;}String b=new String(x.getRequestBody().readAllBytes(),StandardCharsets.UTF_8);Player p=player(field(b,"adminMcid"));if(p==null||!p.isOp()){send(x,403,"application/json","{\"error\":\"operator MCID required\"}");return;}try{String result=finance.configureAutoDividend(p,field(b,"company"),Double.parseDouble(field(b,"amount")),Long.parseLong(field(b,"intervalSeconds")));send(x,200,"application/json","{\"result\":"+str(result)+"}");}catch(NumberFormatException e){send(x,400,"application/json","{\"error\":\"invalid numeric input\"}");}}
    private void order(HttpExchange x)throws IOException{if(!x.getRequestMethod().equalsIgnoreCase("POST")){send(x,405,"application/json","{\"error\":\"POST required\"}");return;}String body=new String(x.getRequestBody().readAllBytes(),StandardCharsets.UTF_8);Player p=player(field(body,"mcid"));if(p==null){send(x,400,"application/json","{\"error\":\"MCID must belong to an online player\"}");return;}try{String result=market.placeOrder(p,field(body,"symbol"),field(body,"side"),field(body,"type"),Long.parseLong(field(body,"quantity")),Long.parseLong(field(body,"price")));send(x,200,"application/json","{\"result\":"+str(result)+"}");}catch(NumberFormatException e){send(x,400,"application/json","{\"error\":\"invalid numeric input\"}");}}
    private Player player(String id){try{if(id==null||id.isBlank())return null;Player p=Bukkit.getPlayer(UUID.fromString(id));return p!=null&&p.isOnline()?p:null;}catch(IllegalArgumentException e){return null;}}
    private String summary(){try(Statement s=db.connection().createStatement()){return "{\"companies\":"+count(s,"companies")+",\"orders\":"+count(s,"orders")+",\"cryptos\":"+count(s,"cryptos")+",\"trades\":"+count(s,"trades")+"}";}catch(SQLException e){return "{\"error\":\"database unavailable\"}";}}
    private long count(Statement s,String table)throws SQLException{try(ResultSet r=s.executeQuery("SELECT COUNT(*) FROM "+table)){r.next();return r.getLong(1);}}
    private String query(HttpExchange x,String key){String q=x.getRequestURI().getRawQuery();if(q==null)return "";for(String pair:q.split("&")){String[] v=pair.split("=",2);if(v.length==2&&v[0].equals(key))try{return URLDecoder.decode(v[1],StandardCharsets.UTF_8);}catch(Exception ignored){}}return "";}
    private String field(String body,String key){String marker="\""+key+"\"";int i=body.indexOf(marker);if(i<0)return "";i=body.indexOf(':',i);if(i<0)return "";int a=body.indexOf('"',i);if(a>=0){int z=body.indexOf('"',a+1);return z>0?body.substring(a+1,z):"";}int z=body.indexOf(',',i);return body.substring(i+1,z>0?z:body.length()).replaceAll("[{} ]","");}
    private String str(String v){return v==null?"null":"\""+esc(v)+"\"";}private String esc(String v){return v.replace("\\","\\\\").replace("\"","\\\"");}
    private void staticFile(HttpExchange x,String path)throws IOException{if(path.equals("/")||path.isBlank())path="/index.html";String resource="/webconsole"+path;try(InputStream in=plugin.getResource(resource.substring(1))){if(in==null){send(x,404,"text/plain","Not found");return;}sendBytes(x,200,contentType(path),in.readAllBytes());}}
    private String contentType(String p){return p.endsWith(".css")?"text/css; charset=utf-8":p.endsWith(".js")?"application/javascript; charset=utf-8":"text/html; charset=utf-8";}
    private void send(HttpExchange x,int code,String type,String body)throws IOException{sendBytes(x,code,type,body.getBytes(StandardCharsets.UTF_8));}
    private void sendBytes(HttpExchange x,int code,String type,byte[] body)throws IOException{x.getResponseHeaders().set("Content-Type",type);x.getResponseHeaders().set("X-Content-Type-Options","nosniff");x.getResponseHeaders().set("Cache-Control","no-store");x.sendResponseHeaders(code,body.length);try(OutputStream o=x.getResponseBody()){o.write(body);}}
}
